env:  
  global:
    - secure: "..."                     # replace this with the travis encryption output!
    - GIT_DEPLOY_DIR=public             # default output dir of Hugo (change it, when you use configured it!)
    - GIT_DEPLOY_BRANCH=master          # target branch, replace by "gh-pages" for Github Project Pages
    - GIT_DEPLOY_USERNAME="kotlin.how"   # dummy name
    - GIT_DEPLOY_EMAIL=kotlin.how@gmail.com # replace by your email

branches:
  only:
    - sources                           # for Github Project Pages replace with "master"

install:  
  - rm -rf public || exit 0             # cleanup previous run
script:  
  - binaries/hugo                       # Generate
after_success:  
  - cp .travis.yml public               # all branches need this file
- bash deploy.sh                      # run the deploy
